In [7]:
# ЗАДАНИЕ №1

import numpy as np

In [8]:
# ЗАДАНИЕ №2

# Создаем массив из стандартного списка Python
data_list = [10, 20, 30, 40, 50]
array_from_list = np.array(data_list)

# Генерируем двумерный массив заполненный нулями (размер 3х4)
zero_array = np.zeros(shape=(3, 4))

# Создаем одномерный массив целых чисел от 0 до 9 включительно
range_array = np.arange(start=0, stop=10)

# Выводим полученные массивы
print("Массив из списка:", array_from_list)
print("Массив нулей:\n", zero_array)
print("Массив arange:", range_array)

Массив из списка: [10 20 30 40 50]
Массив нулей:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Массив arange: [0 1 2 3 4 5 6 7 8 9]


In [9]:
# ЗАДАНИЕ №3

# Выводим форму и тип данных массива
print(f"Форма массива (shape): {arr_zeros.shape}")
print(f"Тип данных (dtype): {arr_zeros.dtype}")

Форма массива (shape): (3, 4)
Тип данных (dtype): float64


In [10]:
# ЗАДАНИЕ №4

# Извлечение третьего элемента из массива (индексация начинается с 0)
third_element = arr_list[2]
print("Третий элемент (индекс 2):", third_element)

# Выбор среза массива (элементы с индекса 1 до 4, исключая сам 4-й индекс)
slice_array = arr_list[1:4]
print("Срез [1:4]:", slice_array)

Третий элемент (индекс 2): 30
Срез [1:4]: [20 30 40]


In [11]:
# ЗАДАНИЕ №5

# Умножаем каждый элемент массива на число 2
multiplied_array = arr_list * 2
print("Массив, умноженный на 2:", multiplied_array)

# Суммируем два массива поэлементно
summed_array = arr_list + multiplied_array
print("Сумма массивов:", summed_array)

# Рассчитываем среднее арифметическое всех элементов массива
average_value = np.mean(arr_list)
print("Среднее значение:", average_value)

# Определяем максимальное значение среди элементов массива
max_value = np.max(arr_list)
print("Максимальное значение:", max_value)

Массив, умноженный на 2: [ 20  40  60  80 100]
Сумма массивов: [ 30  60  90 120 150]
Среднее значение: 30.0
Максимальное значение: 50
